/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marketing.mail.ui;

import com.marketing.db.FaceBookDao;
import com.marketing.entity.FaceBook;
import com.marketing.facebook.dto.Group;
import com.marketing.facebook.dto.Page;
import com.marketing.facebook.action.FanPageAction;
import com.marketing.facebook.action.GroupAction;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TUNGLV
 */
public class AddFanpageOrGroup extends javax.swing.JFrame {

    /**
     * Creates new form AddFanpageOrGroup
     */
    public AddFanpageOrGroup() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxType = new javax.swing.JComboBox<>();
        btAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtToken = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRs = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm mới fanpage, group");

        jLabel1.setText("Tên người dùng");

        jLabel2.setText("ID fanpage, group");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Loại");

        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FANPAGE", "GROUP" }));
        cbxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTypeActionPerformed(evt);
            }
        });

        btAdd.setText("Thêm mới");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jLabel4.setText("User token");

        txtToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTokenActionPerformed(evt);
            }
        });

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Kết quả thực hiện");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtToken)
                    .addComponent(txtID)
                    .addComponent(cbxType, 0, 194, Short.MAX_VALUE)
                    .addComponent(txtRs))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            String username = txtUserName.getText().trim();
            String token = txtToken.getText().trim();
            String idFaceBook = txtID.getText().trim();
            // lay thong tin nhap lieu gan vao doi tuong Facebook
            FaceBook face = new FaceBook();
            if (cbxType.getSelectedItem().toString().equals(FaceBook.TYPE_FANPAGE)) {//la fanpage
                face.setType(FaceBook.TYPE_FANPAGE);

                FanPageAction fanPageAction = null;
                if (!idFaceBook.isEmpty() && idFaceBook != null) { //nhap vao id
                    try {
                        face.setIdFacebook(idFaceBook);
                        fanPageAction = new FanPageAction();
                        Page page = fanPageAction.getPageInfoByUserName(token, txtID.getText());
                        face.setName(page.getName());
                    } catch (Exception ex) {
                        Logger.getLogger(AddFanpageOrGroup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {//nhap ten nguoi dung cua trang
                    try {
                        fanPageAction = new FanPageAction();
                        Page page = fanPageAction.getPageInfoByUserName(token, username);
                        face.setIdFacebook(page.getId());
                        face.setName(page.getName());
                    } catch (Exception ex) {
                        Logger.getLogger(AddFanpageOrGroup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                //lay danh sach thanh vien like fanpage
                fanPageAction = new FanPageAction();
                String member = fanPageAction.getMemberOfFanPage(face.getIdFacebook(), token);
                face.setMember(member);
            }
            if (cbxType.getSelectedItem().toString().equals(FaceBook.TYPE_GROUP)) {//la group
                face.setType(FaceBook.TYPE_GROUP);
                 GroupAction groupAction = null;
                if (!idFaceBook.isEmpty() && idFaceBook != null) {//nhap vao id
                    try {
                        face.setIdFacebook(txtID.getText().trim());
                         groupAction = new GroupAction();
                        Group group = groupAction.getGroupInfoByID(token, txtID.getText().trim());
                        face.setIdFacebook(idFaceBook);
                        face.setName(group.getName());
                    } catch (Exception ex) {
                        Logger.getLogger(AddFanpageOrGroup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {//nhap ten nguoi dung cua nhom
                    try {

                         groupAction = new GroupAction();
                        Group group = groupAction.getGroupInfoByUsername(token, username);
                        face.setIdFacebook(group.getId());
                        face.setName(group.getName());
                    } catch (Exception ex) {
                        Logger.getLogger(AddFanpageOrGroup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            //kiem tra xem trang da ton tai trong db hay chua
            FaceBook fb = FaceBookDao.getFaceBook(face);
            if (fb == null) { //du lieu chua co trong db thi insert
                //insert du lieu vao bang TBL_FACEBOOK
                FaceBookDao.insert(face);
                System.out.println("them moi facebook: "+face.getName()+" thanh cong!");
                txtRs.setText("them moi facebook: "+face.getName()+" thanh cong!");
            } else {
                System.out.println("insert error!: trang "+face.getName()+" da ton tai");
                txtRs.setText("insert error!: trang "+face.getName()+" da ton tai");
            }

        } catch (Exception ex) {
            Logger.getLogger(AddFanpageOrGroup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void cbxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DashBoard();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFanpageOrGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFanpageOrGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFanpageOrGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFanpageOrGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFanpageOrGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtRs;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
