/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mail.marketing.ui;

import com.mail.marketing.db.MailSendDao;
import com.mail.marketing.entity.MailSend;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PMDVCNTT
 */
public class AddEmailBlocked extends javax.swing.JFrame {

    /**
     * Creates new form AddEmailBlocked
     */
    public AddEmailBlocked() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMailSend = new javax.swing.JTextArea();
        btAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaMailBlocked = new javax.swing.JTextArea();
        btExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm danh sách mail chặn");

        jLabel1.setText("Danh sách email chặn");

        txtAreaMailSend.setColumns(20);
        txtAreaMailSend.setRows(5);
        txtAreaMailSend.setToolTipText("Danh sách mail gửi cần thêm mail chặn vào mail_blocked, nếu mail bị chặn thì chỉ thêm vào những mail gửi bị chặn, nếu mail nhận là địa chỉ không xác định thì thêm vào tất cả mail gửi \ntrungtammshoa@outlook.com;mshoatoeic@outlook.com;coso1.mshoatoeic@outlook.com\n");
        jScrollPane1.setViewportView(txtAreaMailSend);

        btAdd.setText("Thêm vào danh sách mail gửi");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Danh sách mail gửi");

        txtAreaMailBlocked.setColumns(20);
        txtAreaMailBlocked.setRows(5);
        txtAreaMailBlocked.setToolTipText("Danh sách mail chặn cần thêm vào mail_blocked ngăn cách nhau bằng dấu ;  chú ý nằm trên cùng 1 dòng\nnhiihuynhh535@hmail.com;quynhanhktqt17@gmaik.com;lehuynhduc97@gmail.com;chihangsnsd@gmail.com;nguyenthihonghanh1552001@gmail.com");
        jScrollPane2.setViewportView(txtAreaMailBlocked);

        btExit.setText("Quay lại");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btExit)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        //nhap moi dong 1 dia chi mail can them vao blocked
        //VD:
//        nhiihuynhh535@hmail.com
//        vqtan1994@gmail.com
//        lethuytram6397@gmail.com
//        Daoconghan98@gmail.com
        String[] lstMailBlocked = txtAreaMailBlocked.getText().trim().split("\n");
        //nhap moi dong 1 dia chi mail gui can them vao blocked
        //VD:
//hoa.ms.toeic@gmail.com
//trungtammshoa@outlook.com
//mshoatoeic@outlook.com
//coso1.mshoatoeic@outlook.com
//coso2.mshoatoeic@gmail.com
//coso3.mshoatoeic@gmail.com
//coso4.mshoatoeic@gmail.com
//coso1.mshoatoeic@gmail.com
//coso5.mshoatoeic@gmail.com
//coso6.mshoatoeic@gmail.com
//coso7.mshoatoeic@gmail.com
//coso8.mshoatoeic@gmail.com
        String[] lstMailSend = txtAreaMailSend.getText().trim().split("\n");
        for (String mailSend : lstMailSend) {
            try {
                MailSend mailSend1 = MailSendDao.getMailSendByEmail(mailSend.trim());
                String mailBlocked = mailSend1.getMailBlocked();
                if (mailBlocked == null) {
                    mailBlocked = txtAreaMailBlocked.getText().trim();
                } else {
                    for (String mailLocked : lstMailBlocked) {
                        //kiem tra email blocked da them vao mail_blocked hay chua
                        //chua them thi moi add
                        if (!mailSend1.getMailBlocked().contains(mailLocked.trim())) {
                            mailBlocked = mailBlocked + mailLocked + ";";
                            
                        }else{
                            System.out.println("mail "+mailLocked+" da ton tai trong block list");
                        }
                    }
                }

                mailSend1.setMailBlocked(mailBlocked);
                MailSendDao.updateMailBlocked(mailSend1);
                System.out.println("them mail block vao email "+mailSend1.getEmail()+" thanh cong!");
            } catch (Exception ex) {
                Logger.getLogger(AddEmailBlocked.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        

    }//GEN-LAST:event_btAddActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DashBoard();
    }//GEN-LAST:event_btExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmailBlocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmailBlocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmailBlocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmailBlocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmailBlocked().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaMailBlocked;
    private javax.swing.JTextArea txtAreaMailSend;
    // End of variables declaration//GEN-END:variables
}
